---
title: "The spelling of English numbers"
---

The spelling of English numbers is **about as bizarre and inconsistent** as it gets, from the silent letter \<w\> in *two* to the unwritten /w/ at the start of *one*.

Yet three, five, six, nine and ten are all good clean spellings \[\[ who do exactly what they say on the tin, so them // whose \]\] pronunciation is easily predicted from the spelling and the spelling can be predicted from the sound, at least for people who distinguish 'three' and 'tree' differently.

INSERT MAP OF PEOPLE WHO DON'T DISTINGUISH /TH/ and /t/.

START

including the invisible 'w' in 'one' and the silent 'w'

Let's leave the madness of one til the end and we'll start with 'two'.

## Two

The

\- twelve, twenty

Similar words

\- - Swords

--- (get list of such words +

/w/-dropping

\- not sure if it's been spotted in the literature (need to check)

\- Breakfast with Tiffany

\- twelve, twenty

\- tween, betwixt

\- twain, twelve / twelfth, twenty (twainty),

\- twi-

\- twice

\- twig, twilight, twill, twin, twine, twist, (be)twixt, twofold,

Earlier inflectional system

\- Twegen

\- two = fem / neuter

\- twain = mass (nom & accusative)

\- tweox (for two)

\- insert old inflection system!

Similar words

\- - Swords

--- (get list of such words +

/w/-dropping

\- not sure if it's been spotted in the literature (need to check)

\- Breakfast with Tiffany

\- I had steak with Maryanne

Mark Twain is the pseudonym of American writer and humorist Samuel Langhorne Clemens (1835-1910), who had been a riverboat pilot; he took his pen name from the cry mark twain, the call indicating a depth of two fathoms, from mark (n.1) in a specialized sense of "measured notification (a piece of knotted cloth, etc.) on a lead-line indicating fathoms of depth" (1769) + twain.

## Three

improvvisatore

## Five, six, nine, ten 

Five, six, nine and ten are all simple spellings where their sound can be predicted from their spelling and their spelling the sound.

## Seven

The problem with seven is that it looks like it ought to be rhymed with *even*, when in fact it rhymes with *heaven, Kevin* and *eleven*. Most English consonant letters would be doubled here, as in *redden, ledden*, *essence*, but \<v\> never doubled historically as it used to be a vowel letter, so \<vv\> only occurs in a few modern(ish) slang words such as *navvy* and *savvy*, at word boundaries (*revved*, *bevvied*) or loanwords (*improvvisato*).

absence of \<vv\> making it look like it ought to be rhymed with *even*. Most consonant letters would be doubled

This is a quirk of English, so that we have similar

------------------------------------------------------------------------

The spelling of numbers

Intro

Some severiously fossilised spellings.

How many are regular regular?

\- three, six, nine

\- one, two,

One

\- where did that spelling come from?

Pronunciation

\- LOT v STRUT

\- old v new, might relate to money - monetary,

Coventry etc,

\- list of words for which \<o\> ---\> STRUT or used to

Why the final \<e\>???

\- is it padding?

\- disambiguation from 'an'?

Cognates

\- un, une ; uno,

\- ein

\- aon

\- a, an related

**Two**

\- twelve, twenty

Similar words

\- - Swords

--- (get list of such words +

/w/-dropping

\- not sure if it's been spotted in the literature (need to check)

\- Breakfast with Tiffany

Three

\- nothing to note?

Four

\- variable pronunciation

\- foo-er, doo-er etc.

\- quick clip of a speaker from somewhere like Armagh saying this

\- for, four,

Benford's law

11, 12

Vigesimal & Duodecimal systems?

BOX FOR ALL OF THE NUMBERS

1 - 10 (list ?)

1- 12 (3 x 4 grid?)

1-20

Grid showing similar languages,

Colour scheme vertical & horizontal if possible

\*\*\*

Systems

Data issues

\- Need a searchable pronunciation dictionary online

\- varied by

\- this can work as a project too

\--

Des Ryan

Linguist & Data Scientist

Dublin, Ireland

353-83-0913967

a2dez.net

https://www.linkedin.com/in/drdesryan/

PhD Thesis Principles of English spelling formation

Des Ryan \<a2dez.com\@gmail.com\>

	

Apr 19, 2024, 7:28 PM (4 days ago)

	

to me

The spelling of numbers

Intro

Some severiously fossilised spellings.

How many are regular regular?

\- three, six, nine

\- one, two,

One

\- where did that spelling come from?

Earlier pron survives in:

\- only, atone, alone

\- gud'un, young'un

Rhyming with fun, sun, son ---\> south-west England and spread

https://www.etymonline.com/word/one#etymonline_v_7018

\- Insert map of 'one' from some dialect atlas

An ---\> a

An ---\> one (cf ein (German) etc

Pronunciation

\- LOT v STRUT

\- old v new, might relate to money - monetary,

Coventry etc,

\- list of words for which \<o\> ---\> STRUT or used to

Why the final \<e\>???

\- is it padding?

\- disambiguation from 'an'?

Cognates

\- un, une ; uno,

\- ein

\- aon

\- a, an related

Two

\- twelve, twenty

\- tween, betwixt

\- twain, twelve / twelfth, twenty (twainty),

\- twi-

\- twice

\- twig, twilight, twill, twin, twine, twist, (be)twixt, twofold,

Earlier inflectional system

\- Twegen

\- two = fem / neuter

\- twain = mass (nom & accusative)

\- tweox (for two)

\- insert old inflection system!

Similar words

\- - Swords

--- (get list of such words +

/w/-dropping

\- not sure if it's been spotted in the literature (need to check)

\- Breakfast with Tiffany

\- I had steak with Maryanne

Mark Twain is the pseudonym of American writer and humorist Samuel Langhorne Clemens (1835-1910), who had been a riverboat pilot; he took his pen name from the cry mark twain, the call indicating a depth of two fathoms, from mark (n.1) in a specialized sense of "measured notification (a piece of knotted cloth, etc.) on a lead-line indicating fathoms of depth" (1769) + twain.

Three

\- nothing to note?

\- might to 13 & 30 here

Four

\- variable pronunciation

\- foo-er, doo-er etc.

\- quick clip of a speaker from somewhere like Armagh saying this

\- for, four,

OE feower,

40

Check pronunciation across dialects (

Benford's law

Fifteen, fifty

11, 12

Vigesimal & Duodecimal systems?

13, 30 1/3

Metathesis (get another example)

\- threotene (OE)

\- thritene (ME)

18

\- predates the tendency to retain spelling of input parts

\- find similar example of /tt/ getting reduced to single /t/ or any other consonant pair

Ty

\- tig (OE)

\- twenty, thirty, forty (different from)

\- forty fields, Bull McCabe?

20

\- twenties

\- tw

Ten v teen

\- survivor

\-

100

\- Hund + red

\- hund (OE), hund-teontig!

\- six-score hundred & five-score hundred!

\- touch of the duodecimal system

111 Bilbo Baggins's birthday

BOX FOR ALL OF THE NUMBERS

1 - 10 (list ?)

1- 12 (3 x 4 grid?)

1-20

Grid showing similar languages,

Colour scheme vertical & horizontal if possible

\*\*\*

Systems

Data issues

\- Need a searchable pronunciation dictionary online

\- varied by

\- this can work as a project too

Copyright

\- where to get pictures from?

\- how long a clip can you play?

\- education?

Finance

\- patreon, funding etc.

The

One etymology

https://www.quora.com/Why-are-the-English-words-one-and-once-pronounced-with-an-initial-w-sound-Other-words-which-begin-with-on-say-onus-or-onto-have-an-initial-hard-or-soft-o-sound-and-let-s-not-even-mention-onion-here

a-one, a-two, a-one, two, three, fowa

(add sample from Northern English band, possibly the Beatles?)
